### ISSUE TITLE
add: Issue Templates

### ISSUE THREAD

**Issue by FahimFBA** [FahimFBA/python#1]
Add some relevant issue templates for this repository.

**Comment by sharp119** [comment]
Hi Aditya here,

I'd be happy to help create some issue templates for this repository. Here are my suggestions based on the repository's current structure and goals:

1. **Bug Report**:
   - Description
   - Reproduction Steps
   - Expected Behavior
   - Screenshots (if applicable)
   - System Information (OS, Python version)

2. **Feature Request**:
   - Feature Description
   - Benefits
   - Implementation Suggestions

3. **General Discussion**:
   - Discussion Topic
   - Relevant Information

Would love to get started on this. Please assign this task to me.

**Comment by FahimFBA** [comment]
@sharp119, I have already assigned you.

**Comment by FahimFBA** [comment]
I am closing this issue as it has already been solved by @sharp119 in pull request #2
